# Site settings
title: Blog pessoal
description: Momentos de Viajens
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rafael Tavares
user_description: Um dia aprendi que sonhos existem para tornarem-se realidade. E, desde aquele dia, já não durmo pra descansar. Simplesmente durmo pra sonhar. Walt Disney
user_title: Software Developer
email: rafaeltavaresandrade@gmail.com
twitter_username: rafasmusic
github_username:  RafasTavares
gplus_username:  Rafael Tavares

# Google-analytics
google-analytics: 
  id: "UA-57304637-1"

exclude: ['package.json', 'src' , 'node_modules']
