# Dependencies
markdown:         redcarpet
pygments:         true


# Permalinks
permalink:        pretty

# Setup
title:            Rafael Tavares
tagline:         
description:      Mozillian <&> </br>Web/Mobile Developer
url:              http://rafaeltavares.co

author:
  name:           'Rafael Tavares'
  url:            https://twitter.com/rafasmusic

paginate:         5

# Custom vars

github:
  repo:          https://github.com/rafastavares
  
source:     .
destination: ./_site
paginate_path: 'blog/page:num'
atom_path : /atom.xml