# Dependencies
markdown:         redcarpet
pygments:         true
google-analytics-tracking-id: UA-57304637-1


# Permalinks
permalink:        pretty

# Setup
title:            Rafael Tavares
tagline:          @rafasmusic
description:      Web e Mobile Developer
url:              http://rafaeltavares.co

author:
  name:           'Rafael Tavares'
  url:            https://twitter.com/rafasmusic

paginate:         5

# Custom vars

github:
  repo:          https://github.com/rafastavares
  
source:     .
destination: ./_site
paginate_path: 'blog/page:num'
atom_path : /atom.xml
