# Dependencies
markdown:         kramdown
pygments:         true
google-analytics-tracking-id: UA-57304637-1
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Rafael Tavares
tagline:          rafasmusic
description:      Web e Mobile Developer
url:              http://rafaeltavares.co/old
feedburnerurl: http://feeds.feedburner.com/RafasTavares

# Author
author :
  name : Rafael Tavares
  email : suporte.rafas@gmail.com
  flickr: Rafael Tavares
  github : rafastavares
  twitter : rafastavares
  facebook: rafael.tavares.andrade
  linkedin: Rafael Tavares
  googleplus: RafaelTavaresAndrade
  bitbucket: rafastavares
  stackoverflow: rafasmusic

paginate:         5

# Custom vars
github:
  repo:          https://github.com/rafastavares/old
  
source:     .
destination: ./_site
paginate_path: 'blog/page:num'
atom_path : /atom.xml
